name: masjid_locator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 
  firebase_auth: 
  cloud_firestore:
  firebase_storage: 

  firebase_analytics:
  google_fonts: 
  delightful_toast: ^1.1.0 

  image_picker: 
  provider: ^6.1.2
  location: ^6.0.2
  adhan: ^2.0.0+1
  intl: ^0.19.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  geocoding: ^3.0.0
  flutter_google_maps_webservices: ^1.1.1
  geolocator: ^13.0.1
  uuid:
  http:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
